//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nohros.Ruby {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class ruby : global::System.Configuration.ApplicationSettingsBase {
        
        private static ruby defaultInstance = ((ruby)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ruby())));
        
        public static ruby Default {
            get {
                return defaultInstance;
            }
        }
    }
}
