// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=8fd7408b07f8d2cd.  DO NOT EDIT!

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Nohros.Ruby {
  
  namespace Proto {
    
    public static partial class RubyMessagePacket {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_nohros_ruby_RubyMessagePacket__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::Nohros.Ruby.RubyMessagePacket, global::Nohros.Ruby.RubyMessagePacket.Builder> internal__static_nohros_ruby_RubyMessagePacket__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static RubyMessagePacket() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "ChlydWJ5X21lc3NhZ2VfcGFja2V0LnByb3RvEgtub2hyb3MucnVieRokZ29v" + 
            "Z2xlL3Byb3RvYnVmL2NzaGFycF9vcHRpb25zLnByb3RvGhlydWJ5X21lc3Nh" + 
            "Z2VfaGVhZGVyLnByb3RvIokBChFSdWJ5TWVzc2FnZVBhY2tldBIMCgRzaXpl" + 
            "GAEgASgFEhQKDG1lc3NhZ2Vfc2l6ZRgCIAEoBRIPCgdzZXJ2aWNlGAMgASgJ" + 
            "Ei4KBmhlYWRlchgEIAEoCzIeLm5vaHJvcy5ydWJ5LlJ1YnlNZXNzYWdlSGVh" + 
            "ZGVyEg8KB21lc3NhZ2UYBSABKAlCEkgBwj4NCgtOb2hyb3MuUnVieQ==");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_nohros_ruby_RubyMessagePacket__Descriptor = Descriptor.MessageTypes[0];
          internal__static_nohros_ruby_RubyMessagePacket__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::Nohros.Ruby.RubyMessagePacket, global::Nohros.Ruby.RubyMessagePacket.Builder>(internal__static_nohros_ruby_RubyMessagePacket__Descriptor,
                  new string[] { "Size", "MessageSize", "Service", "Header", "Message", });
          pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
          RegisterAllExtensions(registry);
          global::Google.ProtocolBuffers.DescriptorProtos.CSharpOptions.RegisterAllExtensions(registry);
          global::Nohros.Ruby.Proto.RubyMessageHeader.RegisterAllExtensions(registry);
          return registry;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            global::Google.ProtocolBuffers.DescriptorProtos.CSharpOptions.Descriptor, 
            global::Nohros.Ruby.Proto.RubyMessageHeader.Descriptor, 
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  public sealed partial class RubyMessagePacket : pb::GeneratedMessage<RubyMessagePacket, RubyMessagePacket.Builder> {
    private static readonly RubyMessagePacket defaultInstance = new Builder().BuildPartial();
    public static RubyMessagePacket DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override RubyMessagePacket DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected override RubyMessagePacket ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::Nohros.Ruby.Proto.RubyMessagePacket.internal__static_nohros_ruby_RubyMessagePacket__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<RubyMessagePacket, RubyMessagePacket.Builder> InternalFieldAccessors {
      get { return global::Nohros.Ruby.Proto.RubyMessagePacket.internal__static_nohros_ruby_RubyMessagePacket__FieldAccessorTable; }
    }
    
    public const int SizeFieldNumber = 1;
    private bool hasSize;
    private int size_ = 0;
    public bool HasSize {
      get { return hasSize; }
    }
    public int Size {
      get { return size_; }
    }
    
    public const int MessageSizeFieldNumber = 2;
    private bool hasMessageSize;
    private int messageSize_ = 0;
    public bool HasMessageSize {
      get { return hasMessageSize; }
    }
    public int MessageSize {
      get { return messageSize_; }
    }
    
    public const int ServiceFieldNumber = 3;
    private bool hasService;
    private string service_ = "";
    public bool HasService {
      get { return hasService; }
    }
    public string Service {
      get { return service_; }
    }
    
    public const int HeaderFieldNumber = 4;
    private bool hasHeader;
    private global::Nohros.Ruby.RubyMessageHeader header_ = global::Nohros.Ruby.RubyMessageHeader.DefaultInstance;
    public bool HasHeader {
      get { return hasHeader; }
    }
    public global::Nohros.Ruby.RubyMessageHeader Header {
      get { return header_; }
    }
    
    public const int MessageFieldNumber = 5;
    private bool hasMessage;
    private string message_ = "";
    public bool HasMessage {
      get { return hasMessage; }
    }
    public string Message {
      get { return message_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::CodedOutputStream output) {
      int size = SerializedSize;
      if (HasSize) {
        output.WriteInt32(1, Size);
      }
      if (HasMessageSize) {
        output.WriteInt32(2, MessageSize);
      }
      if (HasService) {
        output.WriteString(3, Service);
      }
      if (HasHeader) {
        output.WriteMessage(4, Header);
      }
      if (HasMessage) {
        output.WriteString(5, Message);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (HasSize) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, Size);
        }
        if (HasMessageSize) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, MessageSize);
        }
        if (HasService) {
          size += pb::CodedOutputStream.ComputeStringSize(3, Service);
        }
        if (HasHeader) {
          size += pb::CodedOutputStream.ComputeMessageSize(4, Header);
        }
        if (HasMessage) {
          size += pb::CodedOutputStream.ComputeStringSize(5, Message);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static RubyMessagePacket ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static RubyMessagePacket ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static RubyMessagePacket ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(pb::CodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RubyMessagePacket ParseFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(RubyMessagePacket prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    public sealed partial class Builder : pb::GeneratedBuilder<RubyMessagePacket, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      RubyMessagePacket result = new RubyMessagePacket();
      
      protected override RubyMessagePacket MessageBeingBuilt {
        get { return result; }
      }
      
      public override Builder Clear() {
        result = new RubyMessagePacket();
        return this;
      }
      
      public override Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::Nohros.Ruby.RubyMessagePacket.Descriptor; }
      }
      
      public override RubyMessagePacket DefaultInstanceForType {
        get { return global::Nohros.Ruby.RubyMessagePacket.DefaultInstance; }
      }
      
      public override RubyMessagePacket BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }
        RubyMessagePacket returnMe = result;
        result = null;
        return returnMe;
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is RubyMessagePacket) {
          return MergeFrom((RubyMessagePacket) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(RubyMessagePacket other) {
        if (other == global::Nohros.Ruby.RubyMessagePacket.DefaultInstance) return this;
        if (other.HasSize) {
          Size = other.Size;
        }
        if (other.HasMessageSize) {
          MessageSize = other.MessageSize;
        }
        if (other.HasService) {
          Service = other.Service;
        }
        if (other.HasHeader) {
          MergeHeader(other.Header);
        }
        if (other.HasMessage) {
          Message = other.Message;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::CodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        pb::UnknownFieldSet.Builder unknownFields = null;
        while (true) {
          uint tag = input.ReadTag();
          switch (tag) {
            case 0: {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag);
              break;
            }
            case 8: {
              Size = input.ReadInt32();
              break;
            }
            case 16: {
              MessageSize = input.ReadInt32();
              break;
            }
            case 26: {
              Service = input.ReadString();
              break;
            }
            case 34: {
              global::Nohros.Ruby.RubyMessageHeader.Builder subBuilder = global::Nohros.Ruby.RubyMessageHeader.CreateBuilder();
              if (HasHeader) {
                subBuilder.MergeFrom(Header);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              Header = subBuilder.BuildPartial();
              break;
            }
            case 42: {
              Message = input.ReadString();
              break;
            }
          }
        }
      }
      
      
      public bool HasSize {
        get { return result.HasSize; }
      }
      public int Size {
        get { return result.Size; }
        set { SetSize(value); }
      }
      public Builder SetSize(int value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder ClearSize() {
        result.hasSize = false;
        result.size_ = 0;
        return this;
      }
      
      public bool HasMessageSize {
        get { return result.HasMessageSize; }
      }
      public int MessageSize {
        get { return result.MessageSize; }
        set { SetMessageSize(value); }
      }
      public Builder SetMessageSize(int value) {
        result.hasMessageSize = true;
        result.messageSize_ = value;
        return this;
      }
      public Builder ClearMessageSize() {
        result.hasMessageSize = false;
        result.messageSize_ = 0;
        return this;
      }
      
      public bool HasService {
        get { return result.HasService; }
      }
      public string Service {
        get { return result.Service; }
        set { SetService(value); }
      }
      public Builder SetService(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasService = true;
        result.service_ = value;
        return this;
      }
      public Builder ClearService() {
        result.hasService = false;
        result.service_ = "";
        return this;
      }
      
      public bool HasHeader {
       get { return result.HasHeader; }
      }
      public global::Nohros.Ruby.RubyMessageHeader Header {
        get { return result.Header; }
        set { SetHeader(value); }
      }
      public Builder SetHeader(global::Nohros.Ruby.RubyMessageHeader value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasHeader = true;
        result.header_ = value;
        return this;
      }
      public Builder SetHeader(global::Nohros.Ruby.RubyMessageHeader.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasHeader = true;
        result.header_ = builderForValue.Build();
        return this;
      }
      public Builder MergeHeader(global::Nohros.Ruby.RubyMessageHeader value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.HasHeader &&
            result.header_ != global::Nohros.Ruby.RubyMessageHeader.DefaultInstance) {
            result.header_ = global::Nohros.Ruby.RubyMessageHeader.CreateBuilder(result.header_).MergeFrom(value).BuildPartial();
        } else {
          result.header_ = value;
        }
        result.hasHeader = true;
        return this;
      }
      public Builder ClearHeader() {
        result.hasHeader = false;
        result.header_ = global::Nohros.Ruby.RubyMessageHeader.DefaultInstance;
        return this;
      }
      
      public bool HasMessage {
        get { return result.HasMessage; }
      }
      public string Message {
        get { return result.Message; }
        set { SetMessage(value); }
      }
      public Builder SetMessage(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder ClearMessage() {
        result.hasMessage = false;
        result.message_ = "";
        return this;
      }
    }
    static RubyMessagePacket() {
      object.ReferenceEquals(global::Nohros.Ruby.Proto.RubyMessagePacket.Descriptor, null);
    }
  }
  
  #endregion
  
}
